name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn

      - name: Build for Production
        run: yarn build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          src: dist/
          dest: s3://${{ secrets.BUCKET_NAME }}/
          args: --region=${{ secrets.AWS_REGION }} --acl=public-read

